### ISSUE TITLE
springboot build jar and run -pkg.jar

### ISSUE THREAD

**Issue by landashu** [nthuemmel/executable-packer-maven-plugin#3]
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at de.ntcomputer.executablepacker.runtime.ExecutableLauncher.main(ExecutableLauncher.java:122)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
        at com.aizuda.easyManagerTool.ToolBootApplication.main(ToolBootApplication.java:14)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 6 more

**Comment by nthuemmel** [comment]
Hi, unfortunately, I'm no longer working with Java and won't be able to update the plugin :(

It's very likely that the plugin just isn't compatible with new Java versions / maven versions or other libraries anymore
